branches:
  only:
    - master

image: macos-mojave

before_build:
  - git lfs install
  - git lfs pull

build_script:
  - bash -x build-macos.sh

artifacts:
  - path: Darkness_Looming_The_Dawn-*.dmg
