linux-release:
  stage: deploy
  only:
    - master
  image:
    name: daewok/sbcl:debian-stretch
    entrypoint: [""]
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update -qq
    - apt-get install -y --no-install-recommends file gcc git libc-dev libdumb1 libffi-dev libflac8 libfreetype6 libgdk-pixbuf2.0-0 libgl1-mesa-glx libglib2.0-0 libgtk2.0-0 libogg0 libopenal1 libopusfile0 libpango-1.0-0 libphysfs1 libpulse0 libtheora0 libvorbis0a libvorbisfile3 libxpm4 pkg-config wget
  script:
    - bash -x build-linux.sh
  artifacts:
    paths:
      - Darkness_Looming_The_Dawn*.AppImage

windows-release:
  stage: deploy
  only:
    - master
  image:
    name: scottyhardy/docker-wine
    entrypoint: [""]
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends git p7zip-full xz-utils zip
  script:
    - bash -x build-windows.sh
  artifacts:
    paths:
      - darkness-looming-the-dawn.zip
