linux-release:
  stage: deploy
  only:
    - master
  image:
    name: daewok/sbcl:debian-stretch-fancy
    entrypoint: [""]
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update -qq
    - apt-get install -y --no-install-recommends ca-certificates file gcc git libc-dev libdumb1 libffi-dev libflac8 libgdk-pixbuf2.0-0 libgl1-mesa-dev libgl1-mesa-glx libglib2.0-0 libglu1-mesa-dev libgtk2.0-0 libice-dev libogg0 libopenal1 libopusfile0 libpango-1.0-0 libphysfs1 libpulse0 libsm-dev libtheora0 libvorbis0a libvorbisfile3 libx11-dev libxcursor-dev libxext-dev libxinerama-dev libxpm4 libxpm-dev libxrandr-dev make pkg-config unzip wget
  script:
    - bash -x build-linux.sh
  artifacts:
    paths:
      - Darkness_Looming_The_Dawn*.AppImage

windows-release:
  stage: deploy
  only:
    - master
  image:
    name: scottyhardy/docker-wine:wine-stable-5.0.0
    entrypoint: [""]
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends git nsis p7zip-full xz-utils zip
  script:
    - bash -x build-windows.sh
  artifacts:
    paths:
      - Darkness_Looming_The_Dawn*.exe
