linux-release:
  stage: deploy
  only:
    - master
  image:
    name: daewok/sbcl:buster
    entrypoint: [""]
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update -qq
    - apt-get install -y --no-install-recommends ca-certificates file gcc git libc-dev libdumb1 libffi-dev libflac8 libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-0 libice-dev libogg0 libopenal1 libopusfile0 libphysfs1 libpng-dev libpulse0 libsm-dev libtheora0 libvorbis0a libvorbisfile3 libwebp-dev libx11-dev libxcursor-dev libxext-dev libxinerama-dev libxpm-dev libxrandr-dev libxss1 make multiarch-support pkg-config unzip wget
    - apt-get remove -y libjpeg62-turbo-dev
  script:
    - bash -x build-linux.sh
  artifacts:
    paths:
      - Darkness_Looming_The_Dawn*.AppImage

windows-release:
  stage: deploy
  only:
    - master
  image:
    name: scottyhardy/docker-wine:stable-5.0.3
    entrypoint: [""]
  before_script:
    - export DEBIAN_FRONTEND="noninteractive"
    - apt-get update -qq
    - apt-get install -y --no-install-recommends git nsis p7zip-full xz-utils zip zstd
  script:
    - bash -x build-windows.sh
  artifacts:
    paths:
      - Darkness_Looming_The_Dawn*.exe
