(in-package :dld)


(defun main ()
  (d2c:with-condition-reporter
    (d2c:start-engine
     "Darkness Looming: The Dawn"
     (mapcar
      #'d2c:make-entity-initializer
      '(((:camera)
         (:coordinate :x 12d0 :y 38d0))
        ((:coordinate :x 0d0 :y 0d0)
         (:map :prefab :map))
        ((:player)
         (:coordinate :x 10d0 :y 24d0)
         (:sprite :prefab :heroine :layers-initially-toggled '(:head :clothes))
         (:character :target-x 10d0 :target-y 24d0)
         (:hp :current 100d0 :maximum 100d0)
         (:mana :current 100d0 :maximum 100d0)
         (:combat :min-damage 1d0 :max-damage 2d0))
        ;; TODO : have the ability to embed this in tmx file
        ((:mob :name "Spiderant")
         (:coordinate :x 9d0 :y 43d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 9d0 :target-y 43d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 17d0 :y 49d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 17d0 :target-y 49d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 19d0 :y 46d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 19d0 :target-y 46d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 29d0 :y 96d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 29d0 :target-y 96d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 34d0 :y 67d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 34d0 :target-y 67d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 36d0 :y 71d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 36d0 :target-y 71d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 39d0 :y 76d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 39d0 :target-y 76d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Zombie")
         (:coordinate :x 22.5d0 :y 101d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 22.5d0 :target-y 101d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))))
     :display-width 800
     :display-height 600
     :display-font "alegreya.otf")))
