(in-package :dld)


(defun main ()
  (d2c:with-condition-reporter
    (d2c:start-engine
     "Darkness Looming: The Dawn"
     (mapcar
      #'d2c:make-entity-initializer
      '(((:camera)
         (:coordinate :x 12d0 :y 38d0))
        ((:coordinate :x 0d0 :y 0d0)
         (:map :prefab :map))
        ((:player)
         (:coordinate :x 10d0 :y 24d0)
         (:sprite :prefab :heroine :layers-initially-toggled '(:head :clothes))
         (:character :target-x 10d0 :target-y 24d0)
         (:hp :current 100d0 :maximum 100d0)
         (:mana :current 100d0 :maximum 100d0)
         (:combat :min-damage 1d0 :max-damage 2d0))
        ((:item :type :great-sword)
         (:coordinate :x 84d0 :y 23d0))
        ;; TODO : have the ability to embed this in tmx file
        ((:mob :name "Spiderant")
         (:coordinate :x 9d0 :y 43d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 9d0 :target-y 43d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 17d0 :y 49d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 17d0 :target-y 49d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 19d0 :y 46d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 19d0 :target-y 46d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 29d0 :y 96d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 29d0 :target-y 96d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 34d0 :y 67d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 34d0 :target-y 67d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 36d0 :y 71d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 36d0 :target-y 71d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 39d0 :y 76d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 39d0 :target-y 76d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Spiderant")
         (:coordinate :x 29d0 :y 61d0)
         (:sprite :prefab :spiderant :layers-initially-toggled '(:body))
         (:character :target-x 29d0 :target-y 61d0 :speed 3d0)
         (:hp :current 15d0 :maximum 15d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 22.5d0 :y 101d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 22.5d0 :target-y 101d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 55d0 :y 88d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 55d0 :target-y 88d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 45d0 :y 106d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 45d0 :target-y 106d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 60d0 :y 66d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 60d0 :target-y 66d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 69d0 :y 66d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 69d0 :target-y 66d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Zombie" :vision-range 5d0)
         (:coordinate :x 37d0 :y 100d0)
         (:sprite :prefab :zombie :layers-initially-toggled '(:body))
         (:character :target-x 37d0 :target-y 100d0 :speed 0.5d0)
         (:hp :current 25d0 :maximum 25d0)
         (:combat :min-damage 2d0 :max-damage 12d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 47d0 :y 70d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 47d0 :target-y 70d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 50d0 :y 115d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 50d0 :target-y 115d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 75d0 :y 41d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 75d0 :target-y 41d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 78d0 :y 48d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 78d0 :target-y 48d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 80d0 :y 24d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 80d0 :target-y 24d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 87d0 :y 40d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 87d0 :target-y 40d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 83d0 :y 30d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 83d0 :target-y 30d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 80d0 :y 38d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 80d0 :target-y 38d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 75d0 :y 25d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 75d0 :target-y 25d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 75d0 :y 20d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 75d0 :target-y 20d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 83d0 :y 22d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 83d0 :target-y 22d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 90d0 :y 38d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 90d0 :target-y 38d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton" :vision-range 7d0)
         (:coordinate :x 91d0 :y 22d0)
         (:sprite :prefab :skeleton :layers-initially-toggled '(:body))
         (:character :target-x 91d0 :target-y 22d0 :speed 1d0)
         (:hp :current 20d0 :maximum 20d0)
         (:combat :min-damage 1d0 :max-damage 10d0))
        ((:mob :name "Skeleton Knight" :vision-range 8d0)
         (:coordinate :x 90d0 :y 30d0)
         (:sprite :prefab :skeleton-knight :layers-initially-toggled '(:body))
         (:character :target-x 90d0 :target-y 30d0 :speed 0.7d0)
         (:hp :current 220d0 :maximum 220d0)
         (:combat :min-damage 4d0 :max-damage 18d0))))
     :display-width 800
     :display-height 600
     :display-font "alegreya.otf")))
